services:
  redis:
    container_name: redis
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/var/lib/redis/data
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    image: mongo:8.0.6-noble
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Mongo123
    volumes:
      - ./data/mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Mongo123
      ME_CONFIG_MONGODB_URL: mongodb://admin:Mongo123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

  postgresProducts:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123
      POSTGRES_DB: supermarket_products
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_products:/var/lib/postgresql/data
      - ./query-postgres/initProduct.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  postgresUsers:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123
      POSTGRES_DB: supermarket_users
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres_users:/var/lib/postgresql/data
      - ./query-postgres/initUser.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  authenticate:
    build: ./microservices/authenticate
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://admin:Mongo123@localhost:27017/sessions?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - app-network

  products:
    build: ./microservices/products
    ports:
      - "4001:4001"
    environment:
      - DATABASE_URL=postgres://postgres:Postgres123@postgresProducts:5432/supermarket_products
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - postgresProducts
    networks:
      - app-network

  users:
    build: ./microservices/users
    ports:
      - "4002:4002"
    environment:
      - DATABASE_URL=postgres://postgres:Postgres123@postgresUsers:5432/supermarket_users
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - postgresUsers
    networks:
      - app-network

  order-processing:
    build: ./microservices/order-processing
    ports:
      - "4003:4003"
    environment:
      - DATABASE_URL=mongodb://admin:Mongo123@mongodb:27017/order_processing?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - mongodb
    networks:
      - app-network

  gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - authenticate
      - products
      - users
      - order-processing
    networks:
      - app-network

volumes:
  postgres_products:
    driver: local
  postgres_users:
    driver: local
  redis_data:
    driver: local
  mongo_data:
    driver: local

networks:
  app-network:
    driver: bridge
